import Head from "next/head";
import Header from "components/header";

export default function Home() {
  return (
    <div className="lg:w-[1024px] mx-auto">
      <Head>
        <title>简历 ｜ 段波文</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className=" lg:flex">
        <div className="flex-1 mx-4 py-4">
          <header className="flex items-center">
            <div className="bg-gray-200 flex-1 h-[1px]" />
            <h5 className=" text-center mx-4 bg-gray-300 font-semibold w-28 py-1 rounded-full">
              经历
            </h5>
            <div className="bg-gray-200 flex-1 h-[1px]" />
            <div />
          </header>
          <section>
            <header className="pt-4 pb-2">
              <h5 className="font-semibold flex justify-between">
                TD SYNNEX 成都研发中心
                <span className="text-sm inline-block px-1 rounded text-primary border-primary font-semibold border">
                  部门研发
                </span>
              </h5>
              <span className="font-semibold text-sm">2017.11 - 至今</span>
            </header>
            <div className="text-sm">
              <p>IT-GUI 前端基础服务开发, 包括：</p>
              <p className="py-2">UI 组件库/基础库</p>
              <ul className="pl-6 list-disc space-y-1 ">
                <li>组件和公用包的日常开发维护</li>
                <li>开发了 less 自定义换肤插件</li>
                <li>开发了 iframe 通信机制的库，支撑了 STELLR 平台升级</li>
                <li>开发了 自动部署/发版的插件，提升了团队效率</li>
              </ul>
            </div>
            <div className="text-sm pt-2">
              <p className="py-2">Dashboard 低代码平台</p>
              <ul className="pl-6 list-disc space-y-1 ">
                <li>
                  开发了 Low-code Layout 系统，支持了 STELLR 平台的报表业务
                </li>
                <li>开发了 Azure/SubscriptionDashboard 等项目</li>
              </ul>
            </div>
          </section>
          <section>
            <header className="pt-4 pb-2">
              <h5 className="font-semibold flex justify-between">
                TD SYNNEX China 官网
                <span className="text-sm inline-block px-1 rounded text-primary border-primary font-semibold border">
                  项目
                </span>
              </h5>
              <span className="font-semibold text-sm">2022.01 - 2022.02</span>
            </header>
            <div className="text-sm">
              <p className="pb-2">我的工作：</p>
              <ul className="pl-6 list-disc space-y-1 ">
                <li>负责官网前端代码实现与优化，参与设计</li>
                <li>兼容 IE11 并支持平板和手机端</li>
              </ul>
            </div>
          </section>
          <section>
            <header className="pt-4 pb-2">
              <h5 className="font-semibold flex justify-between">
                STELLR - 云业务平台
                <span className="text-sm inline-block px-1 rounded text-primary border-primary font-semibold border">
                  项目
                </span>
              </h5>
              <span className="font-semibold text-sm">2019.02 - 至今</span>
            </header>
            <div className="text-sm">
              <p>STELLR 平台主要为客户提供 Azure/Office/Google 等云服务</p>
              <p className="py-2">我的工作：</p>
              <ul className="pl-6 list-disc space-y-1 ">
                <li>参与前端框架的设计，探索支持业务快速迭代的技术并落地</li>
                <li>负责兼容了 JSF 老系统，实现平台的迭代升级</li>
                <li>参与开发了低代码报表系统，减少了前后端的重复工作</li>
                <li>
                  参与开发了 STELLR 平台的迭代升级，完成了一系列业务较复杂页面如
                  Checkout, Contract Management 等
                </li>
              </ul>
            </div>
          </section>

          <section>
            <header className="pt-4 pb-2">
              <h5 className="font-semibold flex justify-between">
                STELLR - STOREFRONT 分销中台
                <span className="text-sm inline-block px-1 rounded text-primary border-primary font-semibold border">
                  项目
                </span>
              </h5>
              <span className="font-semibold text-sm">2018.03 - 2019.02</span>
            </header>
            <div className="text-sm">
              <p>
                STOREFRONT 是一个为分销商提供发布 TD SYNNEX
                产品，以及管理用户的平台
              </p>
              <p className="py-2">我的工作：</p>
              <ul className="pl-6 list-disc space-y-1 ">
                <li>参与项目开发，编写公用组件</li>
                <li>完善 dvajs 框架，使其支持路由级 model</li>
                <li>总结了一些 Immutablejs 的使用注意事项</li>
                <li>总结了一套分割 UI 行为与业务逻辑的规范 并落地为新框架</li>
              </ul>
            </div>
          </section>
        </div>
        <div className="flex-1 mx-4 py-4">
          <header className="flex items-center">
            <div className="bg-gray-200 flex-1 h-[1px]" />
            <h5 className=" text-center mx-4 bg-gray-300 font-semibold w-28 py-1 rounded-full">
              技能
            </h5>
            <div className="bg-gray-200 flex-1 h-[1px]" />
          </header>

          <section>
            <header className="pt-4 pb-2">
              <h5 className="font-semibold flex justify-between">
                Web
                <span className="text-sm inline-block px-1 rounded text-primary border-primary font-semibold border">
                  熟练
                </span>
              </h5>
            </header>
            <ul className="pl-6 list-disc space-y-1 text-sm">
              <li>熟知 JS 基本语法与知识，掌握最新语法和 API</li>
              <li>掌握网页重构需要的 CSS/LESS</li>
              <li>掌握前端框架 React</li>
              <li>熟练使用 TypeScript</li>
            </ul>
          </section>

          <section>
            <header className="pt-4 pb-2">
              <h5 className="font-semibold flex justify-between">
                React
                <span className="text-sm inline-block px-1 rounded text-primary border-primary font-semibold border">
                  掌握
                </span>
              </h5>
            </header>
            <ul className="text-sm pl-6 list-disc space-y-1 ">
              <li>用 React 开发过大型复杂应用，熟知 React 基本原理/性能优化</li>
              <li>熟练使用 React 生态技术， 例如 Redux React-Intl</li>
              <li>熟练使用 Ant Design, Next.js, Tailwind CSS, Storybook</li>
            </ul>
          </section>

          <section>
            <header className="pt-4 pb-2">
              <h5 className="font-semibold flex justify-between">Webpack</h5>
            </header>
            <ul className=" text-sm pl-6 list-disc space-y-1 ">
              <li>熟知 Webpack 原理，开发过 Webpack 插件</li>
              <li>升级了系统框架为 Webpack5</li>
            </ul>
          </section>
          <section>
            <header className="pt-4 pb-2">
              <h5 className="font-semibold flex justify-between">Node</h5>
            </header>
            <ul className="text-sm pl-6 list-disc space-y-1 ">
              <li>熟知一些常用 api，使用 Koa 开发过博客程序</li>
              <li>使用 zx 开发过 git 流程工具</li>
            </ul>
          </section>
          <section>
            <header className="pt-4 pb-2">
              <h5 className="font-semibold flex justify-between">其他</h5>
            </header>
            <ul className="text-sm pl-6 list-disc space-y-1 ">
              <li>
                <a
                  className="text-primary"
                  href="https://github.com/dbwcooper/lessys"
                >
                  lessys
                </a>
                : 高度自定义的换肤工具
              </li>
              <li>
                <a
                  className="text-primary"
                  href="https://github.com/dbwcooper/iframe-auto"
                >
                  iframe-auto
                </a>
                : 处理跨域通信以及 Iframe 滚动条
              </li>
              <li>
                <a
                  className="text-primary"
                  href="https://github.com/dbwcooper/react-ctrl-f"
                >
                  react-ctrl-f
                </a>
                : 用 React 模拟浏览器搜索功能
              </li>
              <li>
                <a
                  className="text-primary"
                  href="https://github.com/dbwcooper/es-dynamic-export"
                >
                  es-export
                </a>
                : 自动生成 export 代码
              </li>
            </ul>
          </section>
        </div>
      </main>
    </div>
  );
}
